Repository Meal-Tiger/Meal-Tiger-Backend, pull requests merged in 2022-11, with the labels that each got.

#21 CI automatic testing with mongoDB and maven
  .github/workflows/docker.yml
  .github/workflows/maven.yml
Labels: enhancement

#22 Implement pagination and sorting
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
Labels: enhancement

#23 Fix pagination
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
Labels: bug, enhancement

#27 Cors implementation
  src/main/java/com/mealtiger/backend/BackendApplication.java
  src/main/java/com/mealtiger/backend/configuration/configs/MainConfig.java
Labels: bug

#30 Implement search
  pom.xml
  src/main/java/com/mealtiger/backend/configuration/ConfigLoader.java
  src/main/java/com/mealtiger/backend/configuration/Configurator.java
  src/main/java/com/mealtiger/backend/configuration/annotations/Config.java
  src/main/java/com/mealtiger/backend/configuration/annotations/ConfigNode.java
  src/main/java/com/mealtiger/backend/configuration/configs/MainConfig.java
  src/main/java/com/mealtiger/backend/configuration/exceptions/NoSuchPropertyException.java
  src/main/java/com/mealtiger/backend/database/configuration/MongoClientConfiguration.java
  src/main/java/com/mealtiger/backend/database/repository/RecipeRepository.java
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/test/java/com/mealtiger/backend/BackendApplicationTests.java
  src/test/java/com/mealtiger/backend/database/repository/RecipeRepositoryTest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
Labels: Enhancement
