Repository Meal-Tiger/Meal-Tiger-Backend, pull requests merged in 2022-12, with the labels that each got.

#40 Implement dto
  src/main/java/com/mealtiger/backend/database/model/recipe/Recipe.java
  src/main/java/com/mealtiger/backend/database/model/recipe/RecipeDTO.java
  src/main/java/com/mealtiger/backend/database/repository/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/test/java/com/mealtiger/backend/model/recipe/RecipeTest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
Labels: Bug / Urgent

#41 Fix CORS
  src/main/java/com/mealtiger/backend/BackendApplication.java
Labels: Bug / Low

#46 Move API to correct package
  CHANGELOG.md
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
Labels: HOTFIX

#47 Move RecipeAPI to correct package
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
Labels: HOTFIX

#48 Release-1.0.2-alpha
  CHANGELOG.md
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
Labels: HOTFIX
