Repository Meal-Tiger/Meal-Tiger-Backend, pull requests merged in 2023-01, with the labels that each got.

#54 Image implementation
  pom.xml
  src/main/java/com/mealtiger/backend/configuration/Configurator.java
  src/main/java/com/mealtiger/backend/configuration/configs/ImageConfig.java
  src/main/java/com/mealtiger/backend/configuration/exceptions/InvalidConfigPropertyException.java
  src/main/java/com/mealtiger/backend/database/configuration/MongoClientConfiguration.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Recipe.java
  src/main/java/com/mealtiger/backend/database/model/recipe/RecipeDTO.java
  src/main/java/com/mealtiger/backend/imageio/ImageAdapterFactory.java
  src/main/java/com/mealtiger/backend/imageio/ImageAdapterFactoryConfiguration.java
  src/main/java/com/mealtiger/backend/imageio/adapters/BitmapAdapter.java
  src/main/java/com/mealtiger/backend/imageio/adapters/GIFAdapter.java
  src/main/java/com/mealtiger/backend/imageio/adapters/ImageAdapter.java
  src/main/java/com/mealtiger/backend/imageio/adapters/JPEGAdapter.java
  src/main/java/com/mealtiger/backend/imageio/adapters/PNGAdapter.java
  src/main/java/com/mealtiger/backend/imageio/adapters/WebPAdapter.java
  src/main/java/com/mealtiger/backend/rest/api/ImageAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/ImageIOController.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/main/java/com/mealtiger/backend/rest/exceptions/UploadException.java
  src/test/java/com/mealtiger/backend/imageio/FactoryTest.java
  src/test/java/com/mealtiger/backend/imageio/ImageSource.java
  src/test/java/com/mealtiger/backend/imageio/adapters/BitmapAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/GIFAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/JPEGAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/PNGAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/WebPAdapterTest.java
  src/test/java/com/mealtiger/backend/model/recipe/RecipeTest.java
  src/test/java/com/mealtiger/backend/rest/Helper.java
  src/test/java/com/mealtiger/backend/rest/ImageAPITest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.bmp
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.gif
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.jpg
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.lossless.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.pdf
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.png
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.tiff
  src/test/resources/com/mealtiger/backend/imageio/testImages/DefaultTestImage/TestImage.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.bmp
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.gif
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.jpg
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.lossless.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.png
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.tiff
  src/test/resources/com/mealtiger/backend/imageio/testImages/Flower/TestImage.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.bmp
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.gif
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.jpg
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.lossless.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.png
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.tiff
  src/test/resources/com/mealtiger/backend/imageio/testImages/PiggyBank/TestImage.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.bmp
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.gif
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.lossless.webp
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.png
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.tiff
  src/test/resources/com/mealtiger/backend/imageio/testImages/TransparentTestImage/TestImage.webp
Labels: Feature

#61 Implement authorization
  .github/workflows/maven.yml
  pom.xml
  src/main/java/com/mealtiger/backend/authentication/AuthenticationConfiguration.java
  src/main/java/com/mealtiger/backend/authentication/CustomJwtAuthenticationConverter.java
  src/main/java/com/mealtiger/backend/configuration/configs/AuthenticationConfig.java
  src/main/java/com/mealtiger/backend/database/model/image_metadata/ImageMetadata.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Recipe.java
  src/main/java/com/mealtiger/backend/database/model/recipe/RecipeDTO.java
  src/main/java/com/mealtiger/backend/database/repository/ImageMetadataRepository.java
  src/main/java/com/mealtiger/backend/rest/api/ImageAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/ImageIOController.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/test/java/com/mealtiger/backend/authentication/CustomJwtAuthenticationConverterTest.java
  src/test/java/com/mealtiger/backend/rest/ImageAPITest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
  src/test/java/com/mealtiger/backend/rest/controller/ImageIOControllerTest.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
Labels: Enhancement

#65 Implement validation ingredients
  src/main/java/com/mealtiger/backend/database/model/recipe/Ingredient.java
  src/main/java/com/mealtiger/backend/database/model/recipe/RecipeDTO.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RecipeDTOTest.java
Labels: Enhancement

#69 Implement ratings for recipes
  src/main/java/com/mealtiger/backend/database/model/recipe/Rating.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Recipe.java
  src/main/java/com/mealtiger/backend/database/repository/RecipeRepository.java
  src/main/java/com/mealtiger/backend/rest/api/ImageAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RatingAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/main/java/com/mealtiger/backend/rest/error_handling/CustomResponseEntityExceptionHandler.java
  src/main/java/com/mealtiger/backend/rest/error_handling/exceptions/RatingOwnRecipeException.java
  src/main/java/com/mealtiger/backend/rest/error_handling/exceptions/UploadException.java
  src/main/java/com/mealtiger/backend/rest/model/rating/AverageRatingResponse.java
  src/main/java/com/mealtiger/backend/rest/model/rating/RatingRequest.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeRequest.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeResponse.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RecipeTest.java
  src/test/java/com/mealtiger/backend/database/repository/RecipeRepositoryTest.java
  src/test/java/com/mealtiger/backend/rest/RatingAPITest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
  src/test/java/com/mealtiger/backend/rest/SampleSource.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
  src/test/java/com/mealtiger/backend/rest/model/RatingRequestTest.java
  src/test/java/com/mealtiger/backend/rest/model/RecipeRequestTest.java
Labels: Enhancement

#71 Add image cors configuration
  src/main/java/com/mealtiger/backend/BackendApplication.java
  src/main/java/com/mealtiger/backend/rest/CORSConfiguration.java
Labels: Bug / Medium

#73 Set location header and body on status code created
  src/main/java/com/mealtiger/backend/database/model/image_metadata/ImageMetadata.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Rating.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Recipe.java
  src/main/java/com/mealtiger/backend/database/repository/RecipeRepository.java
  src/main/java/com/mealtiger/backend/rest/CORSConfiguration.java
  src/main/java/com/mealtiger/backend/rest/api/ImageAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RatingAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/main/java/com/mealtiger/backend/rest/error_handling/CustomResponseEntityExceptionHandler.java
  src/main/java/com/mealtiger/backend/rest/model/QueriedObject.java
  src/main/java/com/mealtiger/backend/rest/model/Request.java
  src/main/java/com/mealtiger/backend/rest/model/Response.java
  src/main/java/com/mealtiger/backend/rest/model/rating/AverageRatingResponse.java
  src/main/java/com/mealtiger/backend/rest/model/rating/RatingRequest.java
  src/main/java/com/mealtiger/backend/rest/model/rating/RatingResponse.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeRequest.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeResponse.java
  src/test/java/com/mealtiger/backend/SampleSource.java
  src/test/java/com/mealtiger/backend/database/model/image_metadata/validation/ImageValidatorTest.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RatingTest.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RecipeTest.java
  src/test/java/com/mealtiger/backend/database/repository/RecipeRepositoryTest.java
  src/test/java/com/mealtiger/backend/rest/ImageAPITest.java
  src/test/java/com/mealtiger/backend/rest/RatingAPITest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
  src/test/java/com/mealtiger/backend/rest/controller/ImageIOControllerTest.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
  src/test/java/com/mealtiger/backend/rest/model/RecipeRequestTest.java
Labels: Enhancement

#74 Configurator improvement
  src/main/java/com/mealtiger/backend/authentication/AuthenticationConfiguration.java
  src/main/java/com/mealtiger/backend/configuration/ConfigLoader.java
  src/main/java/com/mealtiger/backend/configuration/Configurator.java
  src/main/java/com/mealtiger/backend/configuration/annotations/Config.java
  src/main/java/com/mealtiger/backend/configuration/annotations/ConfigNode.java
  src/main/java/com/mealtiger/backend/configuration/configs/AuthenticationConfig.java
  src/main/java/com/mealtiger/backend/configuration/configs/DatabaseConfig.java
  src/main/java/com/mealtiger/backend/configuration/configs/ImageConfig.java
  src/main/java/com/mealtiger/backend/configuration/configs/MainConfig.java
  src/main/java/com/mealtiger/backend/configuration/configs/RestConfig.java
  src/main/java/com/mealtiger/backend/database/configuration/MongoClientConfiguration.java
  src/main/resources/configuration-samples/auth.sample.yml
  src/main/resources/configuration-samples/database.sample.yml
  src/main/resources/configuration-samples/image.sample.yml
  src/main/resources/configuration-samples/main.sample.yml
  src/main/resources/configuration-samples/rest.sample.yml
  src/test/java/com/mealtiger/backend/configuration/ConfigurationTest.java
  src/test/java/com/mealtiger/backend/configuration/configs/TestConfig.java
Labels: Enhancement

#77 Separate integration tests from unit tests
  .github/workflows/maven.yml
  pom.xml
  src/main/java/com/mealtiger/backend/configuration/Configurator.java
  src/test/java/com/mealtiger/backend/authentication/CustomJwtAuthenticationConverterTest.java
  src/test/java/com/mealtiger/backend/configuration/ConfigurationTest.java
  src/test/java/com/mealtiger/backend/database/model/image_metadata/validation/ImageValidatorTest.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RatingTest.java
  src/test/java/com/mealtiger/backend/database/model/recipe/RecipeTest.java
  src/test/java/com/mealtiger/backend/database/repository/RecipeRepositoryTest.java
  src/test/java/com/mealtiger/backend/imageio/FactoryTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/BitmapAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/GIFAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/JPEGAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/PNGAdapterTest.java
  src/test/java/com/mealtiger/backend/imageio/adapters/WebPAdapterTest.java
  src/test/java/com/mealtiger/backend/rest/ImageAPITest.java
  src/test/java/com/mealtiger/backend/rest/RatingAPITest.java
  src/test/java/com/mealtiger/backend/rest/RecipeAPITest.java
  src/test/java/com/mealtiger/backend/rest/controller/ImageIOControllerTest.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
  src/test/java/com/mealtiger/backend/rest/model/RatingRequestTest.java
  src/test/java/com/mealtiger/backend/rest/model/RecipeRequestTest.java
Labels: Chore

#81 Fix /image/** and /images not being authenticated
  src/main/java/com/mealtiger/backend/authentication/AuthenticationConfiguration.java
  src/test/java/com/mealtiger/backend/rest/ImageAPITest.java
Labels: Bug / Urgent

#85 Fix #84
  CHANGELOG.md
  README.md
  pom.xml
  src/main/java/com/mealtiger/backend/configuration/Configurator.java
  src/test/java/com/mealtiger/backend/configuration/ConfigurationTest.java
  src/test/java/com/mealtiger/backend/configuration/configs/TestConfig.java
Labels: Bug / Medium

#94 Fix #88
  Dockerfile
  src/main/java/com/mealtiger/backend/rest/api/ImageAPI.java
Labels: Bug / Urgent

#93 Fix #90
  src/main/java/com/mealtiger/backend/configuration/configs/ImageConfig.java
Labels: Bug / Medium

#92 Fix #87
  src/main/java/com/mealtiger/backend/configuration/configs/ImageConfig.java
  src/main/java/com/mealtiger/backend/rest/controller/ImageIOController.java
Labels: Bug / Urgent

#91 Fix #89
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
Labels: Bug / Urgent

#97 Fix cors mappings do not include put and delete
  CHANGELOG.md
  pom.xml
  src/main/java/com/mealtiger/backend/rest/CORSConfiguration.java
Labels: Bug / Urgent

#99 Fix #98
  src/main/java/com/mealtiger/backend/rest/controller/RecipeController.java
  src/main/java/com/mealtiger/backend/rest/error_handling/CustomResponseEntityExceptionHandler.java
  src/main/java/com/mealtiger/backend/rest/error_handling/exceptions/RatingException.java
  src/main/java/com/mealtiger/backend/rest/error_handling/exceptions/RatingOwnRecipeException.java
  src/test/java/com/mealtiger/backend/rest/RatingAPITest.java
  src/test/java/com/mealtiger/backend/rest/controller/RecipeControllerTest.java
Labels: Bug / Urgent

#100 Update to Spring Boot 3.0.2
  pom.xml
  src/main/java/com/mealtiger/backend/authentication/AuthenticationConfiguration.java
  src/main/java/com/mealtiger/backend/database/model/image_metadata/validation/ImageArrayValidator.java
  src/main/java/com/mealtiger/backend/database/model/image_metadata/validation/ImageExists.java
  src/main/java/com/mealtiger/backend/database/model/image_metadata/validation/ImageValidator.java
  src/main/java/com/mealtiger/backend/database/model/image_metadata/validation/ImagesExist.java
  src/main/java/com/mealtiger/backend/database/model/recipe/Ingredient.java
  src/main/java/com/mealtiger/backend/rest/api/RatingAPI.java
  src/main/java/com/mealtiger/backend/rest/api/RecipeAPI.java
  src/main/java/com/mealtiger/backend/rest/api/UserAPI.java
  src/main/java/com/mealtiger/backend/rest/error_handling/CustomResponseEntityExceptionHandler.java
  src/main/java/com/mealtiger/backend/rest/model/rating/RatingRequest.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeRequest.java
  src/main/java/com/mealtiger/backend/rest/model/user/UserInformationRequest.java
  src/test/java/com/mealtiger/backend/imageio/FactoryTest.java
  src/test/java/com/mealtiger/backend/rest/model/RatingRequestTest.java
  src/test/java/com/mealtiger/backend/rest/model/RecipeRequestTest.java
  src/test/java/com/mealtiger/backend/rest/model/UserInformationRequestTest.java
Labels: Chore

#104 Optimize dockerfile
  Dockerfile
  pom.xml
Labels: Enhancement

#103 Added validation messages where missing
  src/main/java/com/mealtiger/backend/database/model/recipe/Ingredient.java
  src/main/java/com/mealtiger/backend/rest/model/recipe/RecipeRequest.java
  src/main/java/com/mealtiger/backend/rest/model/user/UserInformationRequest.java
Labels: Bug / Low

#106 Change work directory in dockerfile
  Dockerfile
Labels: Bug / Urgent
